const translations: Record<string, string> = {
  "Legal insights — Vũ Khang": "法律视角 — Vũ Khang",
  "Articles on new regulations, practical application and the issues businesses encounter.":
    "了解法规动态、实际应用与企业面临的法律问题。",
  "Vũ Khang — Legal counsel in Vietnam": "Vũ Khang — 越南法律咨询",
  "Vũ Khang · Legal counsel": "Vũ Khang · 法律咨询",
  Understand: "深入理解",
  "the matter.": "您的问题。",
  "Decide with": "审慎决策，",
  "confidence.": "从容前行。",
  "A clear legal perspective on the decisions that matter — from business operations to protecting your rights and interests.":
    "为重要决策提供清晰的法律视角，涵盖企业经营与权益保护。",
  "Talk to Vũ Khang": "联系 Vũ Khang",
  "Explore expertise": "了解专业领域",
  "Discover Vũ Khang": "了解 Vũ Khang",
  "Start with what you need": "从您的需求出发",
  "Find the right expertise": "寻找适合的专业支持",
  "Meet the legal team": "了解律师团队",
  "Request a consultation": "申请咨询",
  "About Vũ Khang": "关于 Vũ Khang",
  "The law, understood\nin your context.": "结合您的实际情况理解法律。",
  "Behind every legal matter is an objective, a concern and a decision that deserves careful consideration.":
    "每个法律问题背后，都有需要认真考虑的目标、关切与决策。",
  "Understanding the context is the starting point for identifying the key issues, assessing the options and clarifying the next step.":
    "理解背景，是确定关键问题、评估选择和明确下一步的起点。",
  "Areas of practice": "专业领域",
  "Focused perspectives.\nAn informed approach.": "深入分析，审慎选择。",
  "Explore the scope of support for the issues that matter to you.":
    "了解与您关注的问题相关的支持范围。",
  "All expertise": "全部专业领域",
  "Ho Chi Minh City skyline at sunset": "胡志明市日落时分的天际线",
  "In a changing\nbusiness landscape.": "与商业环境的变化同行。",
  "Expertise information is being prepared.": "专业领域信息正在整理中。",
  "Getting started": "如何开始",
  "Clarity from the\nfirst conversation.": "从首次沟通起，明确方向。",
  "A focused journey, from understanding your needs to agreeing on the next step.":
    "从理解需求到商定下一步，让沟通更有重点。",
  "Start a conversation": "开始沟通",
  "Understand the context": "了解背景",
  "Share your matter, objectives and the timeline you have in mind.":
    "请说明您的问题、目标和预期时间安排。",
  "Clarify the scope": "明确范围",
  "Discuss relevant documents, the scope of support and engagement terms.":
    "沟通相关材料、支持范围和服务条件。",
  "Agree on next steps": "商定下一步",
  "Appointments and work are confirmed following discussion.":
    "预约与工作安排须经沟通后另行确认。",
  "People & perspectives": "团队与观点",
  "Our people": "律师团队",
  "Expertise begins\nwith people.": "专业始于人才。",
  "Explore lawyer profiles and their areas of practice.":
    "了解律师履历及其专业领域。",
  "Find a lawyer": "查找律师",
  "Legal insights": "法律视角",
  "Read further.\nSee more clearly.": "深入阅读，清晰理解。",
  "Explore legal perspectives on the topics that interest you.":
    "按您关注的主题浏览法律内容。",
  "Explore insights": "浏览法律视角",
  "Briefly describe your matter. Submitting a request does not confirm an appointment or establish a lawyer–client relationship.":
    "请简要说明您的问题。提交申请不代表预约已确认，也不代表建立律师与客户关系。",
  "What happens next": "下一步",
  "Once your request is saved, a reference will appear on screen. A team member must contact you separately to confirm an appointment.":
    "申请保存成功后，页面将显示参考编号。工作人员需另行联系您确认预约。",
  "Please do not include confidential documents, identity information or detailed case files in this form.":
    "请勿通过此表单提交保密文件、身份证明信息或详细案件材料。",
  "Find expertise, people and insights. Vietnamese queries work with or without accents.":
    "查找专业领域、律师和文章。支持带或不带声调的越南语搜索。",
  "Search terms": "搜索关键词",
  "For example: investment, contracts…": "例如：投资、合同……",
  Search: "搜索",
  "results for": "条结果，关键词：",
  "Result type": "结果类型",
  All: "全部",
  "Search pagination": "搜索结果分页",
  Previous: "上一页",
  Next: "下一页",
  "Try a shorter phrase or a related topic.": "请尝试更短的关键词或相关主题。",
  "Understand the context before proposing a direction.":
    "先了解背景，再讨论方向。",
  "The firm profile is awaiting confirmed details about its organisation, practice and people.":
    "公司介绍正在等待组织、执业范围和团队的正式确认信息。",
  "Development content — awaiting approval": "开发内容 — 待审核",
  "Tell us what you need.": "请告诉我们您的需求。",
  "Office details, telephone numbers and email addresses will appear after confirmation by the firm.":
    "办公地址、电话及电子邮箱将在公司确认后公布。",
  "This policy has not yet been approved for publication.":
    "此政策尚未获准正式发布。",
  "Clear information.\nInformed choices.": "信息清晰，选择有据。",
  "Explore the practice areas before submitting your request.":
    "提交申请前，可先了解专业领域。",
  "Explore support for the issues your business faces.":
    "了解与企业经营问题相关的支持范围。",
  "The translation of this content is not yet published.":
    "此内容的译文尚未发布。",
  "Sample practice areas — scope awaiting confirmation":
    "示例专业领域 — 服务范围待确认",
  "Search this list": "搜索此列表",
  "Search by name or keyword…": "按姓名或关键词搜索……",
  "Clear filter": "清除筛选",
  "matching results": "条匹配结果",
  "No verified content is available yet.": "目前尚无已核实的公开内容。",
  Pagination: "分页",
  "Back to listing": "返回列表",
  "Sample service content — not officially published":
    "服务示例内容 — 尚未正式发布",
  "When to start a conversation": "何时适合开始沟通",
  "When your business needs to clarify rights, obligations or options before making a decision. An initial conversation helps identify the issues, relevant documents and an appropriate scope.":
    "当企业需要在决策前明确权利、义务或可选方案时，初步沟通有助于确定问题、相关材料和适当范围。",
  "Proposed scope of support": "拟议支持范围",
  "How to begin": "如何开始",
  "Briefly describe the context, objectives and expected timeline. Scope, fees and the responsible lawyer are determined following discussion and agreement.":
    "请简要说明背景、目标和预期时间。服务范围、费用和负责律师须经沟通商定。",
  Updated: "更新日期",
  "Scope of support": "支持范围",
  Sources: "参考来源",
  "Talk to us": "联系我们",
  "A clear perspective\non your matter.": "为您的问题提供清晰视角。",
  "Send a request with your selected area. Appointments are confirmed separately.":
    "提交包含所选领域的申请。预约须另行确认。",
  "Geometric lines of a contemporary glass building": "现代玻璃建筑的几何线条",
  "A clear perspective.\nA sound foundation.": "清晰的视角，稳固的基础。",
  "Illustrative architecture": "建筑示意图片",
  "Client guide": "客户指南",
  "Clarity from preparing your enquiry to agreeing the scope of work.":
    "从准备咨询到商定工作范围，让每一步更清晰。",
  "Starting an enquiry": "开始咨询申请",
  "Frequently asked questions": "常见问题",
  "Ready to talk?": "准备好沟通了吗？",
  "Briefly describe your needs to start the enquiry process.":
    "请简要说明需求，以便开始受理流程。",
  "Send an enquiry": "提交咨询申请",
  Privacy: "隐私政策",
  Terms: "使用条款",
  "We could not submit your request. Please try again.":
    "未能提交申请，请重试。",
  "Connection failed. Your entries are preserved; please try again.":
    "连接失败。已保留您填写的内容，请重试。",
  "Request received": "已收到申请",
  "Please complete this field.": "请填写此项。",
  "Full name *": "姓名 *",
  "Enter at least 2 characters.": "请至少输入2个字符。",
  "Enter a valid email, such as name@company.com.":
    "请输入有效邮箱，例如 name@company.com。",
  "Phone number": "电话号码",
  "Use digits, spaces and +, -, ( ).": "请使用数字、空格及 +、-、( )。",
  "Preferred date (optional)": "期望日期（可选）",
  "Area of interest": "关注领域",
  "Briefly describe your matter *": "请简要说明您的问题 *",
  "Please describe your matter in at least 15 characters.":
    "请至少输入15个字符。",
  "15–3,000 characters. Do not include confidential information.":
    "15至3,000个字符。请勿包含保密信息。",
  "Read the privacy notice": "阅读隐私说明",
  "Terms of use": "使用条款",
  "I agree to the use of the information above to process and contact me about this request. *":
    "我同意将上述信息用于受理本次申请并就此与我联系。*",
  "Your consent is required to process this request.": "受理申请需要您的同意。",
  "Sending…": "正在发送……",
  "Send request": "提交申请",
  Home: "首页",
  "Information in preparation": "信息正在准备中",
  "Content will appear once verification and publication approval are complete.":
    "内容完成核实并获准发布后将显示在此处。",
  "Contact us": "联系我们",
  "Understand the issues, consult the sources and prepare for an informed conversation.":
    "了解问题、查阅来源，为深入沟通做好准备。",
  "Knowledge library": "知识库",
  "Read with purpose.\nUnderstand the context.": "有重点地阅读，结合背景理解。",
  "Read reference material alongside its sources and update date. For a specific matter, discuss the facts and applicable scope.":
    "请结合参考来源和更新日期阅读。针对具体事项，应另行沟通事实与适用范围。",
  "Search articles": "搜索文章",
  "What would you like to understand?": "您希望了解什么？",
  Topic: "主题",
  "All topics": "全部主题",
  "matching articles": "篇匹配文章",
  "Clear filters": "清除筛选",
  "min read · estimated": "分钟阅读 · 估计",
  Read: "阅读",
  "No matching articles": "未找到匹配文章",
  "Articles are being prepared and reviewed": "文章正在编写与审核中",
  "You can read the client guide or send an enquiry while editorial content is being prepared.":
    "专业内容完善期间，您可阅读客户指南或提交咨询申请。",
  "Read the client guide": "阅读客户指南",
  "Article pagination": "文章分页",
  "From information to your matter": "从知识到您的具体问题",
  "Articles do not replace advice on your specific circumstances. Mention your objectives and relevant deadlines in your enquiry; do not include confidential files.":
    "文章不能替代基于具体情况的咨询。提交申请时，请说明目标和相关期限，勿附保密文件。",
  "Explore the people, professional backgrounds and areas of practice behind each conversation.":
    "了解团队成员、职业背景及专业领域。",
  "People of Vũ Khang": "Vũ Khang 团队",
  "Know the expertise.\nMeet the person behind it.":
    "了解专业，认识负责的律师。",
  "Search by name, language or area of interest. Each profile helps you understand professional experience before making an enquiry.":
    "按姓名、语言或关注领域查找。提交申请前，可通过履历了解律师的专业背景。",
  "This profile does not yet have a published translation.":
    "此履历尚无已发布译文。",
  "Name or keyword": "姓名或关键词",
  "Name, language, role…": "姓名、语言、职务……",
  "Practice area": "专业领域",
  "All practice areas": "全部专业领域",
  "Sort names": "姓名排序",
  "Find people": "查找律师",
  "matching profiles": "份匹配履历",
  "No matching profiles": "未找到匹配履历",
  "Our team profiles are being prepared": "团队履历正在整理中",
  "Try a shorter name or select all practice areas.":
    "请尝试较短姓名或选择全部专业领域。",
  "Profiles will appear after verification and publication approval. You can still submit an enquiry for review and assignment.":
    "履历完成核实并获准发布后将显示。您仍可提交咨询需求，以便受理和安排联系。",
  "View all profiles": "查看全部履历",
  "People pagination": "团队分页",
  "Start with your matter": "从您的问题出发",
  "Not sure who to speak to?": "不确定应与谁沟通？",
  "Share your needs and area of interest. Acceptance and the responsible contact are confirmed following discussion.":
    "请说明需求和关注领域。是否受理及负责人员须经沟通后确认。",
  "Draft — not yet in effect": "草案 — 尚未生效",
  "For review in this development version. Missing operational details must be confirmed before publication.":
    "此内容用于开发版本审核。正式发布前须确认缺失的运营信息。",
  Contents: "目录",
  Author: "作者",
  Qualifications: "职业资历",
  Languages: "使用语言",
  Location: "工作地点",
  Office: "办公室",
  "Contact details": "联系信息",
  "Application deadline": "申请截止日期",
  "Applications for this position are closed.": "此职位已截止接收申请。",
  "Apply by email": "通过电子邮件申请",
  "On this page": "本页内容",
  "When can we help?": "何时需要支持？",
  "Our approach": "处理思路",
  "Legal counsel · Vietnam": "法律咨询 · 越南",
  "Main navigation": "主导航",
  Consultation: "咨询",
  Expertise: "专业领域",
  "Find a way forward\nfor your matter.": "为您的问题寻找下一步方向。",
  "View all expertise": "查看全部专业领域",
  "Close expertise menu": "关闭专业领域菜单",
  "Mobile navigation": "移动端导航",
  "Your next step\nstarts with clarity.": "下一步，从清晰开始。",
  "Tell us about your matter to start a focused conversation.":
    "请告诉我们您的问题，以便展开有重点的沟通。",
  "Understand the matter. Decide with confidence.":
    "深入理解问题，审慎作出决定。",
  "Explore Vũ Khang": "了解 Vũ Khang",
  Connect: "联系",
  Industries: "行业",
  Careers: "招聘",
  "Request an appointment": "申请预约",
  "Back to top": "返回顶部",
  "Our firm": "关于我们",
  People: "律师团队",
  Experience: "项目经验",
  Insights: "法律视角",
  Contact: "联系",
  Articles: "文章",
  "Vietnamese typography specimen": "越南语字体示例",
  "Related expertise": "相关专业领域",
  "Related people": "相关律师",
  "Related experience": "相关经验",
  "Related insights": "相关文章",
  "Skip to content": "跳转至正文",
  "Close menu": "关闭菜单",
  "Open menu": "打开菜单",
  "Investment & corporate": "投资与企业",
  "Dispute resolution": "争议解决",
  "Contracts & transactions": "合同与交易",
  "Technology & data": "技术与数据",
  "Intellectual property & technology": "知识产权与技术",
  "Contracts & commerce": "合同与商事",
  "From investment decisions to the everyday operation of your business.":
    "从投资决策到企业日常经营。",
  "Understand the issues, assess your options and prepare a resolution strategy.":
    "明确问题，评估方案，为争议处理做好准备。",
  "Clarify rights, obligations and risks before you sign.":
    "签署前明确权利、义务和风险。",
  "Protect intellectual assets and establish a foundation for digital operations.":
    "保护知识资产，为数字化业务奠定基础。",
  "Business establishment and structuring": "企业设立与架构",
  "Transaction and contract review": "交易与合同审查",
  "Corporate governance and compliance": "公司治理与合规",
  "Case and evidence assessment": "案件及证据评估",
  "Negotiation and mediation": "协商与调解",
  "Preparation for proceedings": "诉讼材料准备",
  "Contract drafting and review": "合同起草与审查",
  "Negotiation support": "谈判支持",
  "Contract performance issues": "合同履行问题",
  "Intellectual asset review": "知识产权资产审查",
  "Technology contracts": "技术合同",
  "Data processing assessment": "数据处理评估",
  Call: "拨打",
  "Chat on Zalo with": "通过 Zalo 联系",
  "Quick contact": "快速联系",
  "opens in a new tab": "在新标签页中打开",
  "Illustrative content shown to preview the layout — not the firm's official information":
    "示例内容，仅用于预览版面，并非本所正式发布的信息",
  "Or choose the area closest to your matter": "或选择与您的问题最接近的领域",
  "Illustrative profiles shown to preview the layout — these are not the firm's people. Edit or replace them with verified profiles in the CMS.":
    "以下为用于预览版面的示例档案，并非本所人员。请在 CMS 中修改，或替换为已核实的律师档案。",
};
export default translations;
