/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    pages: Page;
    services: Service;
    industries: Industry;
    lawyers: Lawyer;
    experience: Experience;
    articles: Article;
    categories: Category;
    offices: Office;
    recognitions: Recognition;
    careers: Career;
    media: Media;
    'consultation-requests': ConsultationRequest;
    'notification-outbox': NotificationOutbox;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    lawyers: LawyersSelect<false> | LawyersSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    offices: OfficesSelect<false> | OfficesSelect<true>;
    recognitions: RecognitionsSelect<false> | RecognitionsSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'consultation-requests': ConsultationRequestsSelect<false> | ConsultationRequestsSelect<true>;
    'notification-outbox': NotificationOutboxSelect<false> | NotificationOutboxSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'reviewer' | 'publisher' | 'reception';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  /**
   * Dùng trang có đường dẫn home để thay banner trang chủ. Ảnh di động có thể để trống để dùng chung ảnh desktop. Tọa độ 0–100%; 50% là giữa ảnh. Xem trước cả hai màn hình trước khi xuất bản.
   */
  banner?: {
    desktopImage?: (number | null) | Media;
    mobileImage?: (number | null) | Media;
    desktopX?: number | null;
    desktopY?: number | null;
    mobileX?: number | null;
    mobileY?: number | null;
    fit?: ('cover' | 'contain') | null;
    shade?: number | null;
    caption?: string | null;
  };
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  credit: string;
  rights: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  audience?: string | null;
  process?:
    | {
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  scope?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  lawyers?: (number | Lawyer)[] | null;
  experience?: (number | Experience)[] | null;
  articles?: (number | Article)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers".
 */
export interface Lawyer {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  position: string;
  portrait?: (number | null) | Media;
  qualifications?: string | null;
  languages?: string | null;
  services?: (number | Service)[] | null;
  office?: (number | null) | Office;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices".
 */
export interface Office {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  disclosureApproval: string;
  services?: (number | Service)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  author?: (number | null) | Lawyer;
  categories?: (number | Category)[] | null;
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  audience?: string | null;
  process?:
    | {
        heading: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognitions".
 */
export interface Recognition {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Mỗi bản ngôn ngữ có quy trình duyệt và xuất bản riêng. Dùng cùng mã liên kết bản dịch và đường dẫn cho hai ngôn ngữ.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  slug: string;
  language: 'vi' | 'en' | 'zh';
  translationKey: string;
  reviewState?: ('working' | 'pending' | 'approved') | null;
  isSample?: boolean | null;
  summary: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blocks?:
    | (
        | {
            visible?: boolean | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            visible?: boolean | null;
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            visible?: boolean | null;
            heading: string;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
      )[]
    | null;
  location?: string | null;
  closingDate?: string | null;
  applicationEmail?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-requests".
 */
export interface ConsultationRequest {
  id: number;
  reference: string;
  idempotencyKey: string;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  language?: string | null;
  message: string;
  consentAt: string;
  status?: ('received' | 'contacting' | 'confirmed' | 'closed') | null;
  preferredDate?: string | null;
  confirmedAt?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox".
 */
export interface NotificationOutbox {
  id: number;
  request?: (number | null) | ConsultationRequest;
  status?: ('pending' | 'sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'lawyers';
        value: number | Lawyer;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'offices';
        value: number | Office;
      } | null)
    | ({
        relationTo: 'recognitions';
        value: number | Recognition;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'consultation-requests';
        value: number | ConsultationRequest;
      } | null)
    | ({
        relationTo: 'notification-outbox';
        value: number | NotificationOutbox;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  banner?:
    | T
    | {
        desktopImage?: T;
        mobileImage?: T;
        desktopX?: T;
        desktopY?: T;
        mobileX?: T;
        mobileY?: T;
        fit?: T;
        shade?: T;
        caption?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  audience?: T;
  process?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  scope?:
    | T
    | {
        item?: T;
        id?: T;
      };
  lawyers?: T;
  experience?: T;
  articles?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  audience?: T;
  process?:
    | T
    | {
        heading?: T;
        description?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lawyers_select".
 */
export interface LawyersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  position?: T;
  portrait?: T;
  qualifications?: T;
  languages?: T;
  services?: T;
  office?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  disclosureApproval?: T;
  services?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  author?: T;
  categories?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offices_select".
 */
export interface OfficesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recognitions_select".
 */
export interface RecognitionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  language?: T;
  translationKey?: T;
  reviewState?: T;
  isSample?: T;
  summary?: T;
  body?: T;
  blocks?:
    | T
    | {
        text?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              visible?: T;
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              visible?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
      };
  location?: T;
  closingDate?: T;
  applicationEmail?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  rights?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-requests_select".
 */
export interface ConsultationRequestsSelect<T extends boolean = true> {
  reference?: T;
  idempotencyKey?: T;
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  language?: T;
  message?: T;
  consentAt?: T;
  status?: T;
  preferredDate?: T;
  confirmedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notification-outbox_select".
 */
export interface NotificationOutboxSelect<T extends boolean = true> {
  request?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName?: string | null;
  englishName?: string | null;
  registration?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  privacyApproved?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  englishName?: T;
  registration?: T;
  phone?: T;
  email?: T;
  address?: T;
  privacyApproved?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}